### ISSUE TITLE
Uploading The Report - How the 'PUBLISHED_REPORT_URL' works?

### ISSUE THREAD

**Issue by tvbishan** [LoremFooBar/reportgenerator-coverage-bitbucket-pipe#3]
I have read the readme and am still unable to figure out how the 'PUBLISHED_REPORT_URL' works.

Will this upload every report file that was generated to the given server or not? Do I need to make any additional changes to upload the report files besides giving the 'PUBLISHED_REPORT_URL'? Readme says "You can use another pipe to upload the report files to your preferred storage provider."

For instance, I have to upload the report files to an Azure Blob container. Then what would be the value of "PUBLISHED_REPORT_URL"?

If you could give me an example, it would be greatly appreciated.

**Comment by LoremFooBar** [comment]
The pipe doesn't handle uploading the report. The value of `PUBLISHED_REPORT_URL` is used to set the link in the build status. Because the build status is created before the report is uploaded, `PUBLISHED_REPORT_URL` should be set to whatever you "predict" the url to be.
When I created the pipe I wanted to create the build status with the report results, and wanted the build status to link to the report html. The easiest way to implement this was to give it the published report link before actually uploading it.

You can see an example for generating a report, then uploading the report to Azure blob storage in [this project's pipeline](https://github.com/LoremFooBar/reportgenerator-coverage-bitbucket-pipe/blob/30af9389910cd3a681cd1e6bbf4ec56f3ae2ac11/bitbucket-pipelines.yml#L37)

**Comment by tvbishan** [comment]
Thank you for your excellent work! I will follow the reference given.
